### ISSUE TITLE
About fan temp

### ISSUE THREAD

**Issue by RobotsAreCrazy** [JamFox/rpi-waveshare-poe-hat-b-script#1]
Hi,

Thanks for doing this it massively helped me, only thing is how do I change the auto on temp?

**Comment by JamFox** [comment]
I havent fiddled with this myself, but its covered in Waveshare's documentation, basically you have to modify their code for the library: https://www.waveshare.com/wiki/PoE_HAT_(B)#Set_the_Fan_Startup_Temperature

Added link in readme as well: https://github.com/JamFox/rpi-waveshare-poe-hat-b-script/commit/f0fdd3be11329ffa6145cbe7ed4bba7a5ddc132c

**Comment by RobotsAreCrazy** [comment]
Any idea where the location of the py script might be?

Update: .poe-hat in home folder -> main.py the fan set to come on at 43°
